package in.tagteen.tagteen.chatting.model;

import in.tagteen.tagteen.chatting.socket.SocketConstants;
import in.tagteen.tagteen.chatting.utils.ChatFactory;
import com.google.gson.annotations.SerializedName;

public class MessageInfo extends Event {

    @SerializedName("content")
    private String message;

    @SerializedName("location")
    private String location;

    @SerializedName("msg_timer")
    private String date;

    @SerializedName("device_type")
    private String deviceType;

    @SerializedName("chat_thumb")
    private String chatThumb = "";

    @SerializedName("media_link")
    private String mediaLink = "";

    @SerializedName("client_chat_id")
    private String clientChatId;

    @SerializedName("chat_type_id")
    private int chatType;

    @SerializedName("sub_chat")
    private String subChat = "";

    @SerializedName("is_private")
    private boolean isPrivateChat;

    @SerializedName("is_group")
    private boolean isGroupChat;

    @SerializedName("group_id")
    private String groupId = "";

    @SerializedName("flag")
    private int flag;

    public MessageInfo() {
        super(SocketConstants.Event.NEW_MESSAGE);
        deviceType = "ANDROID";
        clientChatId = ChatFactory.getAutoGeneratedMsgId();
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public String getLocation() {
        return location;
    }

    public void setLocation(String location) {
        this.location = location;
    }

    public String getDeviceType() {
        return deviceType;
    }

    public void setDeviceType(String deviceType) {
        this.deviceType = deviceType;
    }

    public void setDate(String date) {
        this.date = date;
    }

    public String getDate() {
        return date;
    }

    public String getChatThumb() {
        return chatThumb;
    }

    public void setChatThumb(String chatThumb) {
        this.chatThumb = chatThumb;
    }

    public String getMediaLink() {
        return mediaLink;
    }

    public void setMediaLink(String mediaLink) {
        this.mediaLink = mediaLink;
    }

    public String getClientChatId() {
        return clientChatId;
    }

    public void setClientChatId(String clientChatId) {
        this.clientChatId = clientChatId;
    }

    public int getChatType() {
        return chatType;
    }

    public void setChatType(int chatType) {
        this.chatType = chatType;
    }

    public String getSubChat() {
        return subChat;
    }

    public void setSubChat(String subChat) {
        this.subChat = subChat;
    }

    public boolean isPrivateChat() {
        return isPrivateChat;
    }

    public void setPrivateChat(boolean privateChat) {
        isPrivateChat = privateChat;
    }

    public boolean isGroupChat() {
        return isGroupChat;
    }

    public void setGroupChat(boolean groupChat) {
        isGroupChat = groupChat;
    }

    public String getGroupId() {
        return groupId;
    }

    public void setGroupId(String groupId) {
        this.groupId = groupId;
    }

    public int getFlag() {
        return flag;
    }

    public void setFlag(int flag) {
        this.flag = flag;
    }

}
