package in.tagteen.tagteen;

import android.app.Activity;
import android.os.Bundle;
import android.text.Html;
import android.view.View;
import android.widget.ImageView;
import android.widget.TextView;
import androidx.annotation.Nullable;

/**
 * Created by lovekushvishwakarma on 16/12/17.
 */

public class TermsAndCond extends Activity {

    String value = "<p><b>IMPORTANT – PLEASE READ THESE TERMS CAREFULLY BEFORE USING THE TAGTEEN MOBILE APPLICATION. BY DOWNLOADING, INSTALLING, USING AND CONTINUOUSLY USING THE SERVICE, YOU ACKNOWLEDGE THAT YOU HAVE READ AND UNDERSTOOD THIS AGREEMENT AND THAT YOU AGREE TO BE BOUND BY ITS TERMS. IF YOU DO NOT AGREE TO OUR TERMS, PLEASE DO NOT USE THE SERVICE.</b></p>" +
            "<p>\nBy accepting tagteen Terms of Use, there is a binding legal agreement between <b>Tagteen Media Labs Pvt Ltd</b> (hereinafter referred to as “tagteen” the “Company,” “we,” “us,” or “our”) and <b>You</b> (“you,” “your,” or “yourself”). These terms govern your use of the Company’s website at www.tagteen.in (the “Site”), mobile software applications (the “Mobile TagteenApplication” or sometimes referred as \"Apps\"), which is also collectively referred to as our ‘Service”.</p>" +
            "<p>\n“tagteen” is an invitation only, online social media platform, which offers you instant messaging, media and article uploading and sharing within the community.</p>" +
            "<p><b>Age criteria : 13-29 years old ONLY!</b></p>" +
            "<p>\nYou are not allowed to use this application if you are not between 13 and 29 years of age. Please delete this application immediately, if you are not eligible.</p>" +
            "<p>\nIf you have an existing profile, once you turn 29 your profile will be removed or transferred to another platform with your consent and permission.</p>" +
            "<p>\nYou agree that no joint venture, partnership, employment, or agency relationship exists between you and the Company as a result of these Terms or use of the Service.</p>" +
            "<p><b>\nYour Account</b></p>" +
            "<p>\nAccount Creation: In order to access the full benefits of the Service, you will have to create a verified tagteen account in your mobile device. Tagteen has the authority to cancel your account if your account does not satisfy our verification policies. When creating your account, you must provide accurate and complete information.</p>" +
            "<p>\nYou must be at least 13 years of age to use the Services or submit any information to tagteen. If you are between 13 and 18 years of age, you may only use the Services under the supervision of a parent or legal guardian who agrees to be bound by these Terms. If you are above 29 or younger than 13 then you will not be allowed to use this application.</p>" +
            "<p>\nWe need to verify and confirm your identity until you become a permanent user in tagteen. It is your responsibility to prove that you are who you say you are and you are within the age criteria to be eligible as a permanent user in tagteen. Your account will lapse in 7days after your registration if  we are unable to verify your identity.</p>" +
            "<p>\nYou may never use another\\'s account without permission. By using the Application, you agree to safeguard the confidentiality of your account, password credentials and for limiting access to your mobile device to prevent unauthorized use of your account on the Application. You are completely and solely responsible for the security and activity that occurs on your account, If you suspect or know of any unauthorized use of your log-in credentials or any other breach of security with respect to your Account, you must notify us immediately at: admin@tagteen.in. Although the Company will not be liable for any loss or damage arising from any unauthorized use of your password and/or credentials prior to you notifying the Company of such unauthorized use or loss thereof, you may be liable for the losses of tagteen, or others, due to such unauthorized use. You understand that you are responsible for all data charges you incur by using the Services.</p>" +
            "<p><b>\nYour content</b></p>" +
            "<p>\n1.The Application or Services may allow you to create, upload, share and/ or store content, (including your text, images, voices, stories, articles, messages, information, video, music, third party links, collectively, \"Content\"). You agree to abide by our  Terms and Community Policies and not to post, store, create or otherwise publish or send through the application your content that violates it. Tagteen has the right to delete or remove your content that if it’s not in line with our terms of use and Community Policies.</p>" +
            "<p>\n2.By submitting or posting your Content through the Application or the Services, you agree to and grant tagteen a non-exclusive, royalty-free, irrevocable, worldwide, fully sub-licensable, transferable and perpetual license to use, copy, reformat, modify, publish, translate, create derivative works, display, sell and distribute your Content in any media anytime to other companies, organizations or individuals including tagteen’s marketing and promotional activities.</p>" +
            "<p>\n3.Tagteen does not claim any ownership over the Content, you retain full ownership of the Content and proprietary rights associated with the Content. Tagteen does not guarantee the validity, accuracy or legal status or confidentiality with respect to any Content associated with you and you will be solely responsible to assume all risks arising out of uploading, posting, transfer or disclosure of the Content.</p>" +
            "<p>\n4.You understand that your Content may be displayed publicly. Company does not control, take responsibility for or assume liability for your Content or any loss or damage related to your Content</p>" +
            "<p>\n5.You will be solely responsible for all Content that you upload, transmit, share or display through the Application or Services. You may only post Content that is non-confidential, you have all proprietary rights to post to the Services, is accurate and not misleading or harmful in any manner; and does not and will not violate these Terms or any applicable law, rule or regulation. Subject to applicable laws, upon deletion of the tagteen account, tagteen will delete all your Content from its database and servers within a maximum of 90 days, except to the extent required to be retained by applicable law. Tagteen does not take any responsibility of deletion of your content ( your messages, status updates, profile picture updates and other files shared by you), which might still be stored locally in your contact’s/friend’s device.</p>" +
            "<p><b>\nThird party content</b></p>" +
            "<p>\nCertain content or services made available through the Application or the Services may have been owned, operated, created or shared by other users, publishers, and other third parties including advertisements (\"Third Party Content/ Services\"). You agree and assume all risks and liabilities attached by accessing those Content/Services and tagteen is not responsible or liable for those Third Party Services.  When you access the Third Party Content, you should understand that you are no longer governed by tagteen Terms and Policies and that the terms and policies of those third party sites or services will then apply. </p>" +
            "<p><b>\nIntellectual Property</b></p>" +
            "<p>\nWe respect the intellectual property rights of others, and we expect that you will do the same. That’s why you are expressly forbidden from posting any Content that violates someone else’s intellectual property rights, including, without limitation, copyright, trademarks and other proprietary rights. You acknowledge and agree that the Application, the Services, including without limitation any content available on the Application, all trademarks, service marks and trade names and other intellectual property rights associated therewith, and text, graphics, information, logos, icons, images, sound files, software, other files are the exclusive property of tagteen or its licensors and is protected by applicable laws.</p>" +
            "<p>\nAny use except as specifically permitted under these Terms, including the reproduction, modification, distribution, republication, display or performance, of the content on the Application or the Services is strictly prohibited. We reserve the right to remove User Content alleged to be infringing without prior notice to you and at our sole discretion</p>" +
            "<p>\nSubject to these Terms, you are granted a limited, non-exclusive, non-transferable and revocable license to access and use the Services and Service Materials for your personal, non-commercial use. You agree and understand that you will use the Application and/or Services solely for lawful purposes only; and you will not, nor allow third parties on your behalf to reproduce, duplicate, copy, sell, create derivative works or otherwise exploit for any commercial purpose the Application (including its content) and/ or Services;</p>" +
            "<p><h3>\nPrivacy Policy</h3></p>" +
            "<p>\nAt tagteen we recognize that privacy is significant. This Privacy Policy (\"Policy\") applies to your use of the the application and its services on all platforms (the \"Services\").</p>" +
            "<p>\nWhen using tagteen messenger, nothing is stored in our server.</p>" +
            "<p>\nTagteen has created this Policy to explain how we collect, use and share your information when you use our Application and Services. By using our Service you understand, agree and consent that we are providing a platform for you to post content, including photos, videos, voices, comments, articles and other materials (\"Your Content\"), and to share Your Content publicly.  If You do not agree with this Policy, or with our Terms of Service, do not download, install and / or use the Application.</p>" +
            "<p>\nIf you have any questions about this Privacy Policy, please contact us at: admin@tagteen.in.</p>" +
            "<p><b>\nWhat Kind of Information Do We Collect?</b>" +
            "<p>\nAccount Information: As a part of the registration process, tagteen will allow you to use your mobile number or email  to register in the Application and create an account. When you create an account, we may collect the personal information you provide to us, such as your name, gender, date of birth, school name, school address pin code, hobbies, username, password, email address, picture, or phone number and so on. We do not access your address book or contact list on your phone currently</p>" +
            "<p><b>\nYour Content: </b></p>" +
            "<p>When you are choosing to participate in the use of the Application and the Services, such as registering as a user, messaging other tagteen users, posting status updates, uploading images/videos/articles we collect that information to provide you a service. In order to provide Services you hereby agree to provide tagteen a right to use such information for providing Services and also warrant that you have all requisite rights in your favour to share this information with tagteen. When using tagteen chat messenger none of your messages are stored in our server.</p>" +
            "<p>\n<b>Device Information:</b></p>" +
            "<p>\nWe collect information, which may include the Android ID, Log files, hardware model, operating system and version, mobile network information, browser type and language, IP address etc. about the device you use to access our Services and customise the service for your device</p>" +
            "<p>\n<b>Usage and Log Information:</b></p>" +
            "<p>\nWe collect information about your use of the Services, including access times, date and stamp information, articles and videos viewed and interactions (e.g. heart, like, U Rock cool, comment, share) and other information about your interactions with us, the Services and other users.We use these information to provide, understand, and improve our Services.</p>" +
            "<p><b>\nCookies and Other Tracking Technologies:</b></p>" +
            "<p>We and our service providers use cookies, web beacons, web storage and other technologies to collect information about your use of our Services and your device to improve our Services and your experience. We may use similar technologies to collect information when you interact with services offered by any third party through the Application.</p>" +
            "<p>\n<b>Other Information:</b></p>" +
            "<p>\n We may collect information you submit to communicate with us, for example, when you give us your opinions via feedback, update your account, interact with the Services, apply for a job at our company, communicate with us via third-party sites, We receive information about you and your activities on and off tagteen from third-party partners, such as information from a partner when we jointly offer services or from an advertiser about your experiences or interactions with them.</p>" +
            "<p><b>\nHow We Use and Share Collected Information?</b></p>" +
            "<p>\nWe do not sell Your Information that we collect with anyone for commercial, advertising and or similar marketing purposes without your consent.</p>" +
            "<p>\nWe use and share your information to personalise your experience, to provide, maintain, improve and develop the Service for your device, to provide customer service and support, to identify winners of promotional contests, to change or updates to features of tagteen, to deliver the products and services you request, to send you emails and push notifications, to promote safety and security, to comply with applicable laws or legal obligations, and for analytics and authentication.</p>" +
            "<p>\nWhen you share your content using our Services, you choose the audience who can see what you share. Any information you share with a public audience, can be seen or accessed by everyone in the platform.</p>" +
            "<p>\nWhen you use third-party apps, websites or other services that use, or are integrated with, our Services, they may receive information about you, what you post or share. In addition, when you download or use such third-party services, they can access your public profile information. Information collected by these apps, websites or integrated services is subject to their own terms and policies. We work with third party companies who help us provide and improve our Services for you.</p>" +
            "<p>\nWe want our advertising to be as relevant and useful for you as the other information you find on our Application or Services. We do not share information that personally identifies you like your name, email etc. with advertising or analytics partners and other partners unless you give us permission. These partners must adhere to strict confidentiality obligations in a way that is consistent with this Terms and  Policy and the agreements we enter into with them.</p>" +
            "<p>\n<b>Limitation of liability</b></p>" +
            "<p>\nTo the fullest extent permitted by applicable laws, under no circumstance will tagteen or it’s any company party ( its affiliates, respective directors, employees or agents, contractors, suppliers, licensors) be liable to you or any third party for any special, incidental, indirect, punitive or consequential damages whatsoever, including, but not limited to, damages for loss of profits or loss of data, loss of confidential information, business interruption, loss of privacy, including warranty, contract, tort (including negligence) or otherwise and any other loss whatsoever arising out of or in any way arising from or related to the use of Application, or the inability to use all or part of the Application at any time, or the service materials, including without limitation any damages caused by or resulting from reliance from any information obtained through the services (including personal injury, property damage, death), or any damage resulting from third party content used in connection with the Application even if tagteen and such company party has been advised of the possibility of such damages. Notwithstanding anything to the contrary, our maximum aggregate liability to you for any causes whatsoever, and regardless of the form of action, will at all times be limited to the amount paid by you, if any, for using any Services giving rise to the claim or Rupees one thousand only (Rs. 1000), whichever is lesser.</p>" +
            "<p>\n<b>Warranty Disclaimer</b></p>" +
            "<p>\nYOU EXPRESSLY ACKNOWLEDGE AND AGREE THAT, TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, YOUR USE OF THE APPLICATION OR SERVICES IS AT YOUR SOLE RISK AND DISCRETION. YOU SHALL BE LIABLE FOR ANY CONSEQUENCES WHATSOEVER RESULTING FROM ANYTHING TRANSMITTED OR CAUSED TO BE TRANSMITTED BY YOU, TO OR THROUGH THE APPLICATION. THE COMPANY AND THE COMPANY PARTIES (ITS AFFILIATES, AND THEIR RESPECTIVE OFFICERS, DIRECTORS, EMPLOYEES, AGENTS, SUPPLIERS AND LICENSORS) MAKE NO WARRANTY AGAINST AND WILL NOT BE LIABLE OR RESPONSIBLE FOR ANY OF THESE GIVEN BELOW INCLUDING BUT NOT LIMITED TO THE,</p>" +
            "<p>\n1. ACCURACY, SECURITY, RELIABILITY, COMPLETENESS, APPROPRIATENESS, TIMELINESS OF THE CONTENT AVAILABLE ON THE SERVICE</p>" +
            "<p>\n2.ERRORS, MISTAKES OR OMISSIONS THEREIN, OR FOR ANY DELAYS OR INTERRUPTIONS IN TRANSMISSION OF THE DATA OR STORAGE OF INFORMATION</p>" +
            "<p>\n3.LOSSES OR DAMAGES INCLUDING ANY PERSONAL INJURY ARISING FROM OR IN ANY WAY RELATED TO YOUR ACCESS OR USE OF THE APPLICATION AND/ OR SERVICES</p>" +
            "<p>\n4. ANY CONTENT POSTED, TRANSMITTED, OR OTHERWISE MADE AVAILABLE THROUGH THE APPLICATION AND/ OR SERVICES</p>" +
            "<p>\n5.BUGS, VIRUSES, WHICH MAY BE TRANSMITTED TO OR THROUGH OUR APPLICATION OR SERVICES</p>" +
            "<p>\n6.INTRUSION, DISTORTION, LOSS OR FORGERY OF DATA, ETC DUE TO ACT OF ANY THIRD PARTY, FAILURE OF ANY SOFTWARE AND/OR HARDWARE OR TELECOMMUNICATION SERVICE PROVIDER(S) USED BY US OR ANY OTHER ACT BEYOND OUR REASONABLE CONTROL.</p>" +
            "<p>\n<b>Indemnification</b></p>" +
            "<p>\nTo the maximum extent permitted by applicable law, You agree to defend, indemnify and hold harmless the company and company parties(affiliates, respective officers, directors, contractors, employees and agents), from and against any claims, loss, damages, costs, liabilities and expenses (including, but not limited to, attorney's' fees) arising out of or related to (a) your access to and use (or misuse) of the Services; (b) any User Content or Submission you provide; (c) your violation of these Terms; (d) your violation of any rights of another or of any law; or (e) your negligence and misconduct</p>" +
            "<p>\n<b>Third party disputes</b></p>" +
            "<p>\nTo the fullest extent permitted by law, any dispute you have with any third party arising out of your use of the Service, is directly between you and such third party, and you irrevocably release the Company and it’s Parties ( affiliates, respective officers, directors, contractors, employees and agents) from any and all claims and damages of every kind and nature, known and unknown, arising out of or in any way connected with such disputes.</p>" +
            "<p>\n<b>Entire Agreement</b></p>" +
            "<p>\nYou agree that these Terms constitutes the entire agreement between you and the Company with respect to the subject matter hereof, and supersedes all previous or contemporaneous agreements, whether written or oral, between the parties with respect to the subject matter herein.  </p>" +
            "<p>\n<b>Amendments</b></p>" +
            "<p>\nWe’ll notify you before we make changes to these terms and give you the opportunity to review on the revised terms before continuing to use our Services. Your continued use of the tagteen Services, following notice of the changes to our terms, policies or guidelines, constitutes your acceptance of our amended terms, policies or guidelines.</p>" +
            "<p>\n<b>Waiver</b></p>" +
            "<p>\nIf you breach these terms, and in the event of a failure of the Company to act on or enforce on the breach will not be construed as a waiver of that provision or any other provision in these Terms. </p>" +
            "<p>\n<b>Severability</b></p>" +
            "<p>\nIf any provision of these Terms shall be deemed unlawful, void or for any reason unenforceable, then that provision shall be deemed severable from these Terms and the remainder of these terms shall be valid and enforceable.</p>" +
            "<p>\n<b>Right to Remove</b></p>" +
            "<p>\nYou understand and agree that tagteen reserves the full and absolute right to takedown, delete or remove any content available on the Application in its sole discretion, without any notice to you, for any reason whatsoever including on account of your violation of these Terms, in line with the applicable laws.</p>" +
            "<p>\nCommunications/Contact Us</p>" +
            "<p>\nIf you have any questions or comments about the Services, they may be directed to tagteen at admin@tagteen.in.</p>" +
            "<p>\nBy signing up with us, you agree that you will receive all types of communications whether promotional or otherwise from us via, phone and email.</p>"+
            "<p>\n<h3>Community Policies</b></h3>" +
            "<p>\nPlease read the following carefully, as we have a zero tolerance policy regarding misuse of Content (including your text, images, voices, stories, articles, messages, information, video, music, third party links shared by you, collectively, \"Content\"), and any violation may result in the immediate suspension or termination of your account. </p>" +
            "<p>\nAt tagteen we are committed to maintain a fun, welcoming, and safe community for all our users.  For that reason, we've developed a set of Community Policies, outlined below.</p>" +
            "<p>\nRespect everyone on tagteen, don’t spam people or post nudity</p>" +
            "<p>\n<b>1.No Nudity Or Posting Private Content</b></p>" +
            "<p>\nOverly sexualized Content, indecency and/or obscenity is strictly forbidden on tagteen. Please Remember, Where appropriate, we reserve the right to refer the aforementioned abusive content to local and/or federal law enforcement.</p>" +
            "<p>\nWe don’t allow exposure of any genitalia, whatsoever. However, we do allow photographs of paintings, sculptures, and other art that depicts nude figures. Explicit images or videos of sexual activity are prohibited. We also do not allow any sort of  inappropriate or revealing clothing to be posted on our platform. Sexually suggestive or provocative activity, which includes any sexual gestures, posture, dances, and/or general sexual behavior are strictly prohibited. For safety reasons, there are times when we may remove images that show nude or partially-nude children. Please refrain from the use of Content which invades another person’s privacy or which divulges their private or confidential information.</p>"+
            "<p>\n<b>2. No Bullying, Harassment, Or Hateful Language.</b></p>" +
            "<p>\nHaters Keep out.</p>" +
            "<p>\nWe do not tolerate bullying or harassment and hate speech of any kind purposefully targeting an user or group of individuals, which will be strongly dealt with by tagteen. Such behaviour will result in ban and suspension of user account and such content may be transferred to the law enforcement agencies if required.</p>" +
            "<p>\nWe remove content of violence or attack or discriminatory remarks on anyone based on their race, appearance, ethnicity, nationality, gender identity, sexual orientation, religion or faith and disabilities.This includes specific threats of physical harm as well as threats of theft and vandalism etc.</p>" +
            "<p>\nWe remove content (sharing photos or videos) that targets of physical bullying of a person to degrade or shame them, personal information meant to blackmail or harass someone, and repeated unwanted messages.</p>" +
            "<p>\n<b>3. No Criminal Activity.</b></p>" +
            "<p>\nTagteen is not a place to facilitate or organize any criminal activity, which has the potential to directly or indirectly cause physical or financial harm to people, businesses, animals and properties. We work with law enforcement when we believe there is a genuine risk of physical harm or direct threats to public safety.</p>"+
            "<p>\n<b>4. No Violent, Self Injury, or Graphic Content</b></p>"+
            "<p>\nWe do not allow Content that promotes or encourages physical violence towards yourself or others, and/or graphic content including child/animal abuse, self-mutilation, bodily harm is strictly prohibited. We remove disturbing and graphic images and videos when they are shared for sadistic pleasure or to glorify violence.</p>"+
            "<p>\n<b>5. No Spam</b></p>" +
            "<p>\nPlease respect our community and refrain from spamming anyone, under any circumstances. Failure to comply with this Guideline may result in the immediate termination of your account and permanent ban from using tagteen.</p>"+
            "<p>\n<b>6. No Violation of Copyrights</b></p>"+
            "<p>\nUsers are forbidden from posting any Content that violates someone else’s intellectual property rights, including copyright. We expect you to own all of the content and information you post on tagteen. We ask that you respect copyrights, trademarks, and other legal rights.</p>"+
            "<p><b>\n7. Reporting Abuse</b></p>"+
            "<p>\nTo keep the tagteen community safe and secure, we heavily rely on our vigilant users. If you see something on tagteen that you believe violates our terms and policies, please report it us. If you come across any such content or activity, please report the activity to us via email at: admin@tagteen.in with the offender’s details and a screenshot of the abusive content. On top of that, you can also report or block that user from the app. Our dedicated and prompt team of reviewers will assess the content and  will take appropriate action in dealing with the matter. The penalty for violating our Policies may vary, in our sole discretion, based on the severity of the violation.</p>";


    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.tems_cond_layout);

        TextView textDesc = (TextView) findViewById(R.id.textDesc);
        textDesc.setText(Html.fromHtml(value));
        textDesc.setTextAlignment(View.TEXT_ALIGNMENT_GRAVITY);

        ImageView imageClose = (ImageView) findViewById(R.id.imageClose);
        imageClose.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                finish();
            }
        });

    }
}
